/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define TESTSUITE_PLUGIN_PATH "/home/lzm/Wayland/weston/builddir/tests/test-plugin.so"

#define WESTON_DATA_DIR "/home/lzm/Wayland/weston/tests/../data"

#define WESTON_MODULE_MAP "gl-renderer.so=/home/lzm/Wayland/weston/builddir/libweston/renderer-gl/gl-renderer.so;drm-backend.so=/home/lzm/Wayland/weston/builddir/libweston/backend-drm/drm-backend.so;fbdev-backend.so=/home/lzm/Wayland/weston/builddir/libweston/backend-fbdev/fbdev-backend.so;headless-backend.so=/home/lzm/Wayland/weston/builddir/libweston/backend-headless/headless-backend.so;wayland-backend.so=/home/lzm/Wayland/weston/builddir/libweston/backend-wayland/wayland-backend.so;x11-backend.so=/home/lzm/Wayland/weston/builddir/libweston/backend-x11/x11-backend.so;xwayland.so=/home/lzm/Wayland/weston/builddir/xwayland/xwayland.so;screen-share.so=/home/lzm/Wayland/weston/builddir/compositor/screen-share.so;cms-static.so=/home/lzm/Wayland/weston/builddir/compositor/cms-static.so;cms-colord.so=/home/lzm/Wayland/weston/builddir/compositor/cms-colord.so;systemd-notify.so=/home/lzm/Wayland/weston/builddir/compositor/systemd-notify.so;desktop-shell.so=/home/lzm/Wayland/weston/builddir/desktop-shell/desktop-shell.so;ivi-shell.so=/home/lzm/Wayland/weston/builddir/ivi-shell/ivi-shell.so;hmi-controller.so=/home/lzm/Wayland/weston/builddir/ivi-shell/hmi-controller.so;kiosk-shell.so=/home/lzm/Wayland/weston/builddir/kiosk-shell/kiosk-shell.so;pipewire-plugin.so=/home/lzm/Wayland/weston/builddir/pipewire/pipewire-plugin.so;weston-keyboard=/home/lzm/Wayland/weston/builddir/clients/weston-keyboard;weston-screenshooter=/home/lzm/Wayland/weston/builddir/clients/weston-screenshooter;weston-desktop-shell=/home/lzm/Wayland/weston/builddir/clients/weston-desktop-shell;weston-ivi-shell-user-interface=/home/lzm/Wayland/weston/builddir/clients/weston-ivi-shell-user-interface;weston-test-desktop-shell.so=/home/lzm/Wayland/weston/builddir/tests/weston-test-desktop-shell.so;test-ivi-layout.so=/home/lzm/Wayland/weston/builddir/tests/test-ivi-layout.so;"

#define WESTON_TEST_REFERENCE_PATH "/home/lzm/Wayland/weston/tests/reference"

#define WESTON_TEST_SKIP_IS_FAILURE 0

